server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pdgigs
      auto-index-creation: true

jwt:
  secret: tu-secreto-super-seguro-minimo-32-caracteres-para-hs512-debe-ser-largo
  expiration-ms: 86400000

logging:
  level:
    com.pdgigs: DEBUG