# Application Name
spring.application.name=pdgigs

# Server Configuration
server.port=8080

# MongoDB Configuration
spring.data.mongodb.database=pdgigs

# Multipart File Upload Configuration
spring.codec.max-in-memory-size=10MB

# Logging
logging.level.com.pdgigs=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
