server:
  port: 8080

spring:

  webflux:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  codec:
    max-in-memory-size: 20MB

  data:
    mongodb:
      uri: mongodb://localhost:27017/pdgigs
      auto-index-creation: true

jwt:
  secret: clave-super-secreta-para-desarrollo-2024
  expiration-ms: 86400000

app:
  bootstrap:
    admin:
      email: admin@example.com
      password: admin123

logging:
  level:
    com.pdgigs: DEBUG